all:
  hosts:
    192.168.127.131:               # This is the IP of the target machine (remote machine)
      ansible_ssh_user: jenkins    # User on the target machine (e.g., jenkins)
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa  # Private key on Jenkins server



